=== nmacherey/cxbindings/share/Hollidays.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Hollidays" xmlns:wxg="http://www.example.org/Hollidays" elementFormDefault="qualified">

    <complexType name="personType">
    	<sequence>
    		<element name="address" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="zipcode" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="city" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="country" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="email" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="phone" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="age" type="positiveInteger" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="firstname" type="string" use="required"></attribute>
    	<attribute name="lastname" type="string"></attribute>
    </complexType>

    <complexType name="holidayType">
    	<sequence>
    		<element name="start" type="date" minOccurs="1" maxOccurs="1"></element>
    		<element name="end" type="date" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="holidaysType">
    	<sequence>
    		<element name="personHolidays" type="wxg:personHolidaysType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <element name="holidays" type="wxg:holidaysType"></element>

    <complexType name="personHolidaysType">
    	<sequence>
    		<element name="person" type="wxg:personType" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="holiday" type="wxg:holidayType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== nmacherey/cxbindings/share/demo/holidaysdemo.xml
<?xml version="1.0" encoding="UTF-8"?>
<wxg:holidays xmlns:wxg="http://www.example.org/Hollidays" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Hollidays Hollidays.xsd ">
  <wxg:personHolidays>
    <wxg:person firstname="Toto" lastname="Dupont">
      <wxg:address>6 av des prés</wxg:address>
      <wxg:zipcode>123 CP12</wxg:zipcode>
      <wxg:city>Toto City</wxg:city>
      <wxg:country>France</wxg:country>
      <wxg:email>toto@toto.com</wxg:email>
      <wxg:phone>123456</wxg:phone>
	  <wxg:age>24</wxg:age>
    </wxg:person>
    <wxg:holiday>
      <wxg:start>2010-01-01</wxg:start>
      <wxg:end>2011-01-01</wxg:end>
    </wxg:holiday>
    <wxg:holiday>
      <wxg:start>2011-01-01</wxg:start>
      <wxg:end>2012-01-01</wxg:end>
    </wxg:holiday>
    <wxg:holiday>
      <wxg:start>2013-01-01</wxg:start>
      <wxg:end>2014-01-01</wxg:end>
    </wxg:holiday>
  </wxg:personHolidays>
  <wxg:personHolidays>
    <wxg:person firstname="Tata" lastname="Dupont">
      <wxg:address>6 av des prés</wxg:address>
      <wxg:zipcode>123 CP12</wxg:zipcode>
      <wxg:city>Tata City</wxg:city>
      <wxg:country>France</wxg:country>
      <wxg:email>tata@tata.com</wxg:email>
      <wxg:phone>123456</wxg:phone>
    </wxg:person>
    <wxg:holiday>
      <wxg:start>2010-01-01</wxg:start>
      <wxg:end>2011-01-01</wxg:end>
    </wxg:holiday>
    <wxg:holiday>
      <wxg:start>2011-01-01</wxg:start>
      <wxg:end>2012-01-01</wxg:end>
    </wxg:holiday>
    <wxg:holiday>
      <wxg:start>2013-01-01</wxg:start>
      <wxg:end>2014-01-01</wxg:end>
    </wxg:holiday>
  </wxg:personHolidays>
</wxg:holidays>
